<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="T_BoolCommandTask_1" Id="{ad74609e-ca9f-4daa-9bfd-ae4c36532e52}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_BoolCommandTask_1 EXTENDS T_MockCommandTask IMPLEMENTS I_BoolResultTask
VAR
  _result : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Result" Id="{c0e7327e-7e9b-4f8e-88e2-12ecb1dd9cdd}">
      <Declaration><![CDATA[PROPERTY Result : BOOL
]]></Declaration>
      <Get Name="Get" Id="{b182bdb7-242b-47ac-a801-e9455bf1a487}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Result := _result;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="SetResultValue" Id="{f417e13e-19ad-436b-954d-f2705314b636}">
      <Declaration><![CDATA[METHOD PUBLIC SetResultValue
VAR_INPUT
  value : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_result := value;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="T_BoolCommandTask_1">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="T_BoolCommandTask_1.Result.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="T_BoolCommandTask_1.SetResultValue">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>