site_name: RoboConnect
site_url: https://example.com/
nav:
  - Home: index.md
  - 'Getting Started':
    - 'Setup': 'getting_started.md'
    - 'Example Project': 'exampleProject.md'
    - 'Design Guide': 'design_guide.md'
    - 'RoboConnect Library': 'robo_connect_library.md'

  - 'RoboConnect' :
    - 'I_RoboConnect' : 'robo_connect_I_RoboConnect.md'
    - 'Unit Tests' : 'robo_connect-testing.md'

  - 'RoboConnect Components':
    - 'Connect' : 'robo_connect_connect.md'
    - 'CommandQueue' : 'robo_connect_Command Queue.md'
    - 'CommandStrategy' : 'robo_connect_Command Strategy.md'
    - 'TcpConnection' : 'robo_connect_TcpConnection.md'

  - 'Dobot Implementation' :
    - 'Dobot Setup' : ./Dobot/dobot_set_connection_params.md
    - 'Command List' : ./Dobot/dobot_command_list.md
    - 'RoboConnect Objects': ./Dobot/dobot_robo_connect_Objects.md
    - 'Command Constructor' : ./Dobot/Dobot_Command_Constructor.md

  - 'Unival Implementation' :
    - 'Connect to Unival' : ./Unival/unival-connection.md
    - 'Inherited Properties' : ./Unival/unival-inherited-properties.md

extra_css:
  - stylesheets/extra.css
extra:
  generator: false # remove the footer (generated by mkdocs)
plugins:
  - search
  - glightbox
#theme: readthedocs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: stylesheets/extra.css
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: stylesheets/extra.css
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: 'logo\robot 1.png' # Beckhoff logo
  #logo: 'images/beckhoff_logo_nat_red_a4.png' #Beckhoff transparent logo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - attr_list
  - md_in_html
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: RoboConnect Library